[package]
name = "CLI_Test"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
winapi = { version = "0.3", features = ["libloaderapi"] }


[modules]
buffer_overflow = "src/buffer_overflow.rs"

